
import 'package:checkers_game/l10n/app_localizations.dart';

/// A helper class that facilitates localization of dynamic keys,
/// such as theme names and category names that are stored as strings.
class LocalizationHelper {
  /// Returns the localized name for a board or piece theme based on its [key].
  /// If the key is not found in the mapping, it returns the key itself.
  static String getLocalizedThemeName(String key, AppLocalizations l10n) {
    final themeNames = {
      'themeBoardClassicWood': l10n.themeBoardClassicWood,
      'themeBoardMarble': l10n.themeBoardMarble,
      'themeBoardGreenVelvet': l10n.themeBoardGreenVelvet,
      'themeBoardOceanBlue': l10n.themeBoardOceanBlue,
      'themeBoardAutumn': l10n.themeBoardAutumn,
      'themeBoardGranite': l10n.themeBoardGranite,
      'themeBoardWinterForest': l10n.themeBoardWinterForest,
      'themeBoardRiverStone': l10n.themeBoardRiverStone,
      'themeBoardOttomanTile': l10n.themeBoardOttomanTile,
      'themeBoardEgyptianPapyrus': l10n.themeBoardEgyptianPapyrus,
      'themeBoardRomanMosaic': l10n.themeBoardRomanMosaic,
      'themeBoardJapaneseSakura': l10n.themeBoardJapaneseSakura,
      'themeBoardScandinavianRune': l10n.themeBoardScandinavianRune,
      'themeBoardAztecSunStone': l10n.themeBoardAztecSunStone,
      'themeBoardCelticKnot': l10n.themeBoardCelticKnot,
      'themeBoardVictorian': l10n.themeBoardVictorian,
      'themeBoardGalaxy': l10n.themeBoardGalaxy,
      'themeBoardEnchantedForest': l10n.themeBoardEnchantedForest,
      'themeBoardHellfire': l10n.themeBoardHellfire,
      'themeBoardGlacierKingdom': l10n.themeBoardGlacierKingdom,
      'themeBoardCyberCircuit': l10n.themeBoardCyberCircuit,
      'themeBoardSteampunk': l10n.themeBoardSteampunk,
      'themeBoardAtlantis': l10n.themeBoardAtlantis,
      'themeBoardCanadaSpace': l10n.themeBoardCanadaSpace,
      'themeBoardBlackGold': l10n.themeBoardBlackGold,
      'themeBoardRubyEmerald': l10n.themeBoardRubyEmerald,
      'themeBoardArtDeco': l10n.themeBoardArtDeco,
      'themeBoardRoyalVelvet': l10n.themeBoardRoyalVelvet,
      'themeBoardPorcelain': l10n.themeBoardPorcelain,
      'themeBoardStainedGlass': l10n.themeBoardStainedGlass,
      'themeBoardPearl': l10n.themeBoardPearl,
      'themeBoardBrushStrokes': l10n.themeBoardBrushStrokes,
      'themeBoardMatteBlack': l10n.themeBoardMatteBlack,
      'themeBoardConcreteSteel': l10n.themeBoardConcreteSteel,
      'themeBoardCarbonFiber': l10n.themeBoardCarbonFiber,
      'themeBoardGlass': l10n.themeBoardGlass,
      'themeBoardPaper': l10n.themeBoardPaper,
      'themeBoardDigitalPixel': l10n.themeBoardDigitalPixel,
      'themeBoardPastelGeometry': l10n.themeBoardPastelGeometry,
      'themeBoardMonochromeGradient': l10n.themeBoardMonochromeGradient,
      'themeBoardCandyLand': l10n.themeBoardCandyLand,
      'themeBoardComicBook': l10n.themeBoardComicBook,
      'themeBoard8BitRetro': l10n.themeBoard8BitRetro,
      'themeBoardToyBlocks': l10n.themeBoardToyBlocks,
      'themeBoardRainbow': l10n.themeBoardRainbow,
      'themeBoardGraffiti': l10n.themeBoardGraffiti,
      'themeBoardWatercolor': l10n.themeBoardWatercolor,
      'themeBoardHoneycomb': l10n.themeBoardHoneycomb,
      'themePieceCarvedWood': l10n.themePieceCarvedWood,
      'themePieceIvoryEbony': l10n.themePieceIvoryEbony,
      'themePiecePolishedPebble': l10n.themePiecePolishedPebble,
      'themePieceEarthenware': l10n.themePieceEarthenware,
      'themePieceFrostedGlass': l10n.themePieceFrostedGlass,
      'themePieceRedJasper': l10n.themePieceRedJasper,
      'themePieceBamboo': l10n.themePieceBamboo,
      'themePieceAmber': l10n.themePieceAmber,
      'themePieceIznikTile': l10n.themePieceIznikTile,
      'themePieceLapisLazuli': l10n.themePieceLapisLazuli,
      'themePieceJade': l10n.themePieceJade,
      'themePieceAncientBronze': l10n.themePieceAncientBronze,
      'themePieceObsidian': l10n.themePieceObsidian,
      'themePieceParchment': l10n.themePieceParchment,
      'themePieceTerracotta': l10n.themePieceTerracotta,
      'themePieceIronRune': l10n.themePieceIronRune,
      'themePieceDragonScale': l10n.themePieceDragonScale,
      'themePieceCrystal': l10n.themePieceCrystal,
      'themePieceNeonLights': l10n.themePieceNeonLights,
      'themePieceGhost': l10n.themePieceGhost,
      'themePieceVolcanicMagma': l10n.themePieceVolcanicMagma,
      'themePieceElvenMithril': l10n.themePieceElvenMithril,
      'themePieceOrcishIron': l10n.themePieceOrcishIron,
      'themePieceCosmicDust': l10n.themePieceCosmicDust,
      'themePieceGoldSilver': l10n.themePieceGoldSilver,
      'themePieceBlackPearl': l10n.themePieceBlackPearl,
      'themePieceMalachite': l10n.themePieceMalachite,
      'themePieceVenetianGlass': l10n.themePieceVenetianGlass,
      'themePieceGatsby': l10n.themePieceGatsby,
      'themePieceDiamond': l10n.themePieceDiamond,
      'themePieceRuby': l10n.themePieceRuby,
      'themePieceSapphire': l10n.themePieceSapphire,
      'themePieceModernMinimalist': l10n.themePieceModernMinimalist,
      'themePieceRobotic': l10n.themePieceRobotic,
      'themePieceMetallicGradient': l10n.themePieceMetallicGradient,
      'themePieceGlossyPlastic': l10n.themePieceGlossyPlastic,
      'themePieceHolographic': l10n.themePieceHolographic,
      'themePieceMattePastel': l10n.themePieceMattePastel,
      'themePieceRubber': l10n.themePieceRubber,
      'themePieceLightShadow': l10n.themePieceLightShadow,
      'themePieceConfectionery': l10n.themePieceConfectionery,
      'themePieceChocolate': l10n.themePieceChocolate,
      'themePieceFruitBasket': l10n.themePieceFruitBasket,
      'themePieceGummy': l10n.themePieceGummy,
      'themePieceWatermelon': l10n.themePieceWatermelon,
      'themePieceCosmonaut': l10n.themePieceCosmonaut,
      'themePieceSuperhero': l10n.themePieceSuperhero,
      'themePieceSeashell': l10n.themePieceSeashell,
    };
    return themeNames[key] ?? key;
  }

  /// Returns the localized name of a theme category based on its [rawCategory] string.
  /// If the category name is not found, it returns the raw category string.
  static String getLocalizedCategoryName(String rawCategory, AppLocalizations l10n) {
    final categoryNames = {
      'Klasik & Doğal': l10n.categoryClassicNatural,
      'Kültürel & Tarihi': l10n.categoryCulturalHistorical,
      'Fantastik & Bilimkurgu': l10n.categoryFantasySciFi,
      'Lüks & Sanatsal': l10n.categoryLuxuryArtistic,
      'Modern & Minimalist': l10n.categoryModernMinimalist,
      'Eğlenceli & Renkli': l10n.categoryFunColorful,
    };
    return categoryNames[rawCategory] ?? rawCategory;
  }
}
