// lib/utils/game_saver.dart
import 'dart:convert';
import 'package:checkers_game/domain/models/game_mode.dart';
import 'package:checkers_game/domain/models/game_state.dart';
import 'package:checkers_game/presentation/utils/player_type.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Utility class for persisting and retrieving game states using [SharedPreferences].
/// This allows players to save their progress and resume games later.
class GameSaver {
  /// Generates a unique key for storing a game based on its mode and opponent type.
  /// 
  /// The key format is: `saved_game_{gameModeName}_{opponentTypeName}`
  static String generateKey(GameMode gameMode, PlayerType opponentType) {
    return 'saved_game_${gameMode.name}_${opponentType.name}';
  }

  /// Persists the current [GameState] to local storage.
  /// 
  /// It determines the opponent type (AI vs. Human) and saves the state as a JSON string.
  /// Additionally, it saves the current timestamp for tracking when the game was saved.
  static Future<void> saveGame(GameState gameState) async {
    final prefs = await SharedPreferences.getInstance();
    
    // Determine if the game is against AI or another human.
    final opponentType = gameState.whitePlayerType == PlayerType.ai || gameState.blackPlayerType == PlayerType.ai
        ? PlayerType.ai
        : PlayerType.human;
    
    final key = generateKey(gameState.gameMode, opponentType);

    // Convert the game state to a JSON string for storage.
    final String jsonString = jsonEncode(gameState.toJson());
    await prefs.setString(key, jsonString);
    
    // Save the save date to show in the UI or for management.
    await prefs.setString('${key}_date', DateTime.now().toIso8601String());
  }

  /// Attempts to load a saved [GameState] from local storage for a given mode and opponent type.
  /// 
  /// Returns the reconstructed [GameState] if successful, or `null` if no save exists
  /// or if the data is corrupted. Corrupted data is automatically deleted.
  static Future<GameState?> loadGame(GameMode gameMode, PlayerType opponentType) async {
    final prefs = await SharedPreferences.getInstance();
    final key = generateKey(gameMode, opponentType);
    final String? jsonString = prefs.getString(key);

    if (jsonString != null) {
      try {
        // Parse the stored JSON string back into a GameState object.
        final Map<String, dynamic> jsonMap = jsonDecode(jsonString);
        final loadedState = GameState.fromJson(jsonMap);
        
        // Recalculate possible moves for the loaded state to ensure correctness.
        final possibleMoves = loadedState.rules.getPossibleMoves(loadedState);
        return loadedState.copyWith(possibleMoves: possibleMoves);
      } catch (e) {
        // Clean up corrupted or incompatible save data.
        await prefs.remove(key);
        await prefs.remove('${key}_date');
        return null;
      }
    }
    return null;
  }

  /// Deletes the saved game data for the specified [GameMode] and [PlayerType].
  static Future<void> deleteGame(GameMode gameMode, PlayerType opponentType) async {
    final prefs = await SharedPreferences.getInstance();
    final key = generateKey(gameMode, opponentType);
    await prefs.remove(key);
    await prefs.remove('${key}_date');
  }

  /// Retrieves a map of all saved games and their corresponding save dates.
  /// 
  /// This is used to populate the 'Continue Game' or load menus in the UI.
  /// Keys in the returned map are generated by [generateKey] and values are ISO-8601 date strings.
  static Future<Map<String, String>> getSavedGamesStatus() async {
    final prefs = await SharedPreferences.getInstance();
    final Map<String, String> statusMap = {};
    
    // Iterate through all game modes and check for both PvP and PvE saves.
    for (var mode in GameMode.values) {
      // Check for human vs. human saves.
      var pvpKey = generateKey(mode, PlayerType.human);
      var pvpDate = prefs.getString('${pvpKey}_date');
      if (pvpDate != null) statusMap[pvpKey] = pvpDate;

      // Check for human vs. AI saves.
      var pveKey = generateKey(mode, PlayerType.ai);
      var pveDate = prefs.getString('${pveKey}_date');
      if (pveDate != null) statusMap[pveKey] = pveDate;
    }
    return statusMap;
  }
}
